### PR TITLE
Signup page updated

### PR DESCRIPTION
**Pull request by heli0707**
## Related Issue
#196 

## Description
The redesigned signup page now feature a clean and modern look with rounded borders, balanced spacing, and clear, visually appealing typography. The left section of page is highlighted in a vibrant blue with a welcoming image and message, while the right section hosts the form elements, ensuring a user-friendly experience. The form elements and buttons are styled for consistency and ease of use, making the overall interface intuitive and aesthetically pleasing.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Sahil1786/Petari/assets/95361125/220d9d7a-8a1b-4614-8fb8-22a1844c494f

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
CLOSE ISSUE : #196

### CODE REVIEW

**Comment by heli0707** [comment]
@Sahil1786 merge it!

**Comment by Sahil1786** [comment]
need  to be resolve the ejs file 
Screenshot 2024-07-03 162546

**Comment by heli0707** [comment]
@Sahil1786 
I mentioned the change in the UI part only frontend if you want to fix that I will raise another issue for fixing that backend issue.
in this issue, I just designed the Signup page.

**Comment by Sahil1786** [comment]
i need backend part also

**Pull request closed without merging**
