### PR TITLE
Added dark mode toggle

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
This pull request introduces an animated toggle for switching between dark and light modes in the application. The toggle provides users with a visually appealing way to switch between different color schemes, enhancing the user experience. This feature improves accessibility and customization options for users who prefer different modes based on their preferences or environmental conditions. The implementation follows best practices for user interface design and includes smooth transitions for a seamless experience.

Screenshot 2024-05-18 163314

Screenshot 2024-05-18 163429

### CODE REVIEW

**Comment by Sahil1786** [comment]
show me some demo work

**Comment by thevijayshankersharma** [comment]
@Sahil1786 You can check the edited comment above

**Comment by thevijayshankersharma** [comment]
@Sahil1786 you didn't assign any level label under gssoc.

**Comment by thevijayshankersharma** [comment]
@Sahil1786 ??

**Comment by thevijayshankersharma** [comment]
Please add level labels and GSSOC to the PR
@Sahil1786

**Comment by thevijayshankersharma** [comment]
@sanjay-kv, can't it be level 3 because it took me time to do it? It was my first time contributing to the node.js repo. Please take a look at this PR.

**Pull request merged**
