### PR TITLE
Prototype of Donation Certificate 

### PR DESCRIPTION
**Pull request by gantasrilaitha**
## Related Issue
ISSUE No. #154 

## Description
after user fills donation form & clicks on donate button, user gets customised certificate of donation, with the donation they made. its just a raw template....later it can be enhanced at the frontend

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

[user DashBoard.webm](https://github.com/user-attachments/assets/bebe39c2-2931-4c15-9025-f5381531b8e0)

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by gantasrilaitha** [comment]
@sanjay-kv pls review it

**Comment by Sahil1786** [comment]
this not look like a certificate

**Comment by gantasrilaitha** [comment]
I have just given a raw template....later it can be redesigned...it's a frontend task.

**Comment by Sahil1786** [comment]
you have to design the page

**Comment by Sahil1786** [comment]
you have to design the page

**Pull request closed without merging**
