### PR TITLE
Adding contributing.md

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
### Description
This pull request adds a `CONTRIBUTING.md` file to the PETARI project. The document outlines guidelines for contributing to the project, including reporting issues, creating pull requests, and adhering to the project's code of conduct. The addition of this file aims to provide clear instructions to potential contributors, making the contribution process more efficient and organized.

Screenshot 2024-05-17 165848

### CODE REVIEW

**Comment by Sahil1786** [comment]
Show some demo

**Comment by thevijayshankersharma** [comment]
@Sahil1786 Now?

**Comment by Sahil1786** [comment]
Yes

**Comment by thevijayshankersharma** [comment]
@Sahil1786 You haven't merge it yet

**Pull request closed without merging**
