### PR TITLE
Complete Responsiveness of Contact Form with spaces filled in the page

### PR DESCRIPTION
**Pull request by codercake**
## Related Issue
None

## Description
This pull request enhances the responsiveness of the contact form on the webpage, ensuring it seamlessly adjusts to different screen sizes and devices. The focus is on improving user experience by making the form more accessible and usable across a variety of platforms.

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image
Screenshot 2024-06-21 210823

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by codercake** [comment]
could you review the PR @Sahil1786

**Comment by Sahil1786** [comment]
Give me some time

**Comment by Sahil1786** [comment]
Screenshot 2024-05-17 230039
Screenshot 2024-05-17 230050

**Comment by codercake** [comment]
> Give me some time

any updates?

**Comment by Sahil1786** [comment]
the arrow button taking too space

**Comment by codercake** [comment]
> the arrow button taking too space

it's working fine in my system.

**Comment by Sahil1786** [comment]
I don't want like this arrow button

**Comment by codercake** [comment]
> I don't want like this arrow button

you mean scrolltotop button?

**Comment by codercake** [comment]
removed it, check @Sahil1786

**Comment by Sahil1786** [comment]
This branch has conflicts that must be resolved

**Pull request closed without merging**
