### PR TITLE
update userDashborad, ngoDashboard

### LINKED ISSUE #178: Enhance the user Profile and allow them to edit their profile
**Is your feature request related to a problem? Please describe.**
I want to enhance the user profile page and also want to add the feature to update user profile. So that after signup or login ,  user can update their profile in the future such as name, phone number and address.

**Describe the solution you'd like**
I would like to change the user profile UI something like this.
WhatsApp Image 2024-06-15 at 12 03 07 AM

How do we know when the feature is complete?
The feature is complete when UI and update profile feature is fully implemented and integrated into the project's development workflow.

### PR DESCRIPTION
**Pull request by Laxelspal**
## Related Issue
fix #178 

## Type of PR

- Feature enhancement

## Screenshots / videos (if applicable)

https://github.com/Sahil1786/Petari/assets/136887514/2c4a6a63-f57f-4290-82dc-401e93240787

## Checklist:
- I have performed a self-review of my code
- I have read and followed the Contribution Guidelines.
- I have tested the changes thoroughly before submitting this pull request.
- I have provided relevant issue numbers, screenshots, and videos after making the changes.
- I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Sahil1786** [comment]
you have to change the ui

**Comment by Laxelspal** [comment]
> you have to change the ui

can you suggest tell me , how the ui should be . I have updated according to my choice for both userdashboard and ngodashboard.

**Comment by Sahil1786** [comment]
i need a simple and attractive ui for this also need to be change form the backend

**Comment by Sahil1786** [comment]
Need some time

**Comment by Sahil1786** [comment]
still backend not connected

**Pull request closed without merging**
