### PR TITLE
Fixed Ngo registration problem

### PR DESCRIPTION
**Pull request by its-AkshatJain**

### CODE REVIEW

**Comment by its-AkshatJain** [comment]
I have fixed the ngo registration problem now you can check.

**Comment by Sahil1786** [comment]
show me the demo

**Comment by its-AkshatJain** [comment]
https://github.com/Sahil1786/Petari/assets/129594034/67ee9129-25e6-46c8-9a8d-885e115c911f

**Comment by Sahil1786** [comment]
Ngo registration is still  working

**Pull request closed without merging**
