### PR TITLE
added an  AI-powered system to match food donors with recipients

### PR DESCRIPTION
**Pull request by sanskriti-lal**
## Related Issue
None

## Description
Developed a KNN-based matching algorithm to calculate similarity between donors and recipients using attributes like food type, location, quantity, and timestamp.

## Type of PR

- [ ] Bug fix
- [ X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [X ] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

HOW TO IMPLEMENT -

STEP 1 - Create a webpage to take input from the users.
The input form includes - food_type , location , quantity , timestamp , food_preferences.

STEP 2 - Connect to backend in order to store the submission data in a database.

STEP 3 - convert the donation table which has been taken as input and stored in the above steps into .csv file. I’ve provided code to export the data into .csv file. 

STEP 4 - Implement the model that I've developed, in backend 

STEP 5 - Integrate it with frontend to present the donor-receiver pair table

### CODE REVIEW

**Comment by Sahil1786** [comment]
Show me some video demo

**Comment by sanskriti-lal** [comment]
https://github.com/Sahil1786/Petari/assets/165655543/d4c80eec-f0c8-4db2-9f6b-4f938f27a3ea

@Sahil1786 this is the same model. I've just stimulated my own dataset

**Comment by sanskriti-lal** [comment]
https://github.com/Sahil1786/Petari/assets/165655543/e995ac2b-f1bf-467c-8ec2-fe452eac7624

@Sahil1786 this is the same model, I've just stimulated my own dataset .

**Comment by Sahil1786** [comment]
can you describe  about your contrubution

**Comment by sanskriti-lal** [comment]
I've developed a KNN-based matching algorithm to enhance the process of pairing food donors with recipients. This algorithm uses attributes such as food type, location, quantity, and timestamp to calculate similarity scores, ensuring efficient and effective matches. Additionally, I also outlined a comprehensive implementation plan.

**Comment by sanskriti-lal** [comment]
Also @Sahil1786 can you please assign the respective labels

**Comment by Sahil1786** [comment]
Yea

**Comment by sanskriti-lal** [comment]
@Sahil1786 can you please review it as well

**Comment by sanskriti-lal** [comment]
Hey can you please look into my PR @Sahil1786

**Pull request merged**
