### PR TITLE
"Enhanced Landing Page: Responsive Navbar, Improved UI, and Updated Content"

### PR DESCRIPTION
**Pull request by Pruthaa17**
UI Improvements:

Modified index.ejs to improve the overall layout and design.
Updated style.css to ensure a cohesive and visually appealing user interface.
Added new images to enhance the visual experience of the landing page.
Code Refactoring:

Corrected the file naming convention from index.JS to index.js for consistency.
Enhanced the functionality of index.js to improve performance and user interaction.
Responsive Design:

Implemented responsive design principles to make the landing page and navbar adapt well across different devices and screen sizes.
Ensured that newly added elements, including the navbar and other components, are responsive and user-friendly on mobile, tablet, and desktop devices.
Screenshot (327)
Screenshot (328)
Screenshot (329)

### CODE REVIEW

**Comment by Sahil1786** [comment]
The current UI isn't attractive. Please create a simpler, different UI. We need dashboards, login pages, etc. Drawing inspiration from the homepage UI, make these changes.

**Comment by Pruthaa17** [comment]
Okay ,  I Have a issue and i tried resolving it using many resources but was unable to. On browser the console shows the error saying , 
Failed to load resource: the server responded with a status of 404 (Not Found) about.png:1 
Failed to load resource: the server responded with a status of 404 (Not Found) style.css:1 
Failed to load resource: the server responded with a status of 404 (Not Found) index.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found) public/img/logo.png:1 
Failed to load resource: the server responded with a status of 404 (Not Found) style.css:1 
Failed to load resource: the server responded with a status of 404 (Not Found)

I checked the path and also checked the static file setups , what else can i check for ? Can you please help

**Comment by Sahil1786** [comment]
Did you run MongoDB in your local machine?

**Comment by Pruthaa17** [comment]
Yes I did , still the error is not resolved

**Comment by Sahil1786** [comment]
Write mongod command in your terminal

**Comment by Pruthaa17** [comment]
Yes SIr , I already did

**Comment by Sahil1786** [comment]
Send me the screenshots

**Comment by Pruthaa17** [comment]
Basically I have always worked with  kotlin java spring n mysql  at the backend , never used mongo or node and its my first time contributing to open source ! I have installed node , mongo , ran npm commands tired searching for the solution but still stuck ! If there is any basic configuration thing that i might be missing to look upon ? 

Below is the error that I'm recently facing , 

server is running on port 3000 
Database Connected
Error: Missing credentials for "PLAIN"
    at SMTPConnection._formatError (C:\Users\Prutha Gatlewar\OneDrive\Desktop\Petari\node_modules\nodemailer\lib\smtp-connection\index.js:798:19)
    at SMTPConnection.login (C:\Users\Prutha Gatlewar\OneDrive\Desktop\Petari\node_modules\nodemailer\lib\smtp-connection\index.js:452:38)
    at C:\Users\Prutha Gatlewar\OneDrive\Desktop\Petari\node_modules\nodemailer\lib\smtp-transport\index.js:375:32
    at SMTPConnection.<anonymous> (C:\Users\Prutha Gatlewar\OneDrive\Desktop\Petari\node_modules\nodemailer\lib\smtp-connection\index.js:215:17)
    at Object.onceWrapper (node:events:633:28)
    at SMTPConnection.emit (node:events:519:28)
    at SMTPConnection._actionEHLO (C:\Users\Prutha Gatlewar\OneDrive\Desktop\Petari\node_modules\nodemailer\lib\smtp-connection\index.js:1360:14)
    at SMTPConnection._processResponse (C:\Users\Prutha Gatlewar\OneDrive\Desktop\Petari\node_modules\nodemailer\lib\smtp-connection\index.js:982:20)
    at SMTPConnection._onData (C:\Users\Prutha Gatlewar\OneDrive\Desktop\Petari\node_modules\nodemailer\lib\smtp-connection\index.js:763:14)
    at SMTPConnection._onSocketData (C:\Users\Prutha Gatlewar\OneDrive\Desktop\Petari\node_modules\nodemailer\lib\smtp-connection\index.js:195:44) {
  code: 'EAUTH',
  command: 'API'
} 

Thankful for your time .

**Comment by Pruthaa17** [comment]
Sir please can you specify where

**Comment by Pruthaa17** [comment]
Resolved the issue . Thanks !

**Pull request closed without merging**
