### PR TITLE
Adding list of NGO's

### PR DESCRIPTION
**Pull request by Srishtiii19**
#47 
Screenshot (357)

### CODE REVIEW

**Comment by Srishtiii19** [comment]
hello @Sahil1786, is code visible to you? I was facing some problem in committing the changes so please let me know the same

**Comment by Srishtiii19** [comment]
its the same picture i haven't made changes in the code yet, but i am just asking is code visible to you of ngo's list or not as, i cant see it .
Screenshot (357)

**Comment by Sahil1786** [comment]
I am not getting , which code talking about

**Comment by Srishtiii19** [comment]
> I am not getting , which code talking about

the picture i have sent you isnt  ui, it the actual code that is working i took screenshot of it and then sent you, all i am saying is that can you see the branch that i have committed or only the screenshot is visible to you? 
i was actually facing some issue in committing the branch from my end thats why.

**Comment by Srishtiii19** [comment]
Also i'll change the dummy data and write the actual NGO's list as you said.

**Comment by Sahil1786** [comment]
@Srishtiii19  please connect me on LinkedIn

**Pull request closed without merging**
