### PR TITLE
refactored App.js 

### PR DESCRIPTION
**Pull request by DebmalyaKuila**
Hello PA, I have fixed issue number #8

changes done :

1.moved connection to database logic in db/db.js
2.moved all the routes in app.js into separate files according top their use . They are in a new file called called "routers" which consists of userRotes.js , adminRoutes.js  and NgoRoutes.js
3.moved the email transporter into a separated file "helpers/emailHelpers.js"

image_2024-05-11_235440469

### CODE REVIEW

**Comment by Sahil1786** [comment]
What happened?

**Comment by DebmalyaKuila** [comment]
There was an typo error in my code , which was creating some issues. That's why I closed the PR

**Comment by Sahil1786** [comment]
@DebmalyaKuila there are a admin login problem .please fix the probelm

**Comment by DebmalyaKuila** [comment]
okay , Assign me this issue and I will start working on it. By the way , as App.js_refactor branch is already merged, should I delete this branch?

**Comment by Sahil1786** [comment]
I have created one more issue for login error you can fix on that issue

**Pull request merged**
