### PR TITLE
Updated the about us page 

### PR DESCRIPTION
**Pull request by Atreyiprasad**
i have added vision , approach and process for the website .

### CODE REVIEW

**Comment by Sahil1786** [comment]
show me some demo and fix the branch Conflicting files

**Comment by Atreyiprasad** [comment]
Picture1 
Picture2
Picture3
Picture4
these are some of the changes i made in about us page . Any changes you would like to suggest .

**Comment by Sahil1786** [comment]
need to fix  branch  conflicts

**Comment by Sahil1786** [comment]
This branch has conflicts that must be resolved

**Comment by Atreyiprasad** [comment]
Yes , I am trying to resolve the conflicts . It is taking time because I am very new to open source . I am trying to resolve it as soon as possible .

**Pull request closed without merging**
