### PR TITLE
Feat : Update index.ejs

### LINKED ISSUE #222: Bug : Footer section
**Describe the bug**
Currently copyright year is static that is it is direct copy paste of text , It should be dynamic in nature that is should auto fetch the current year .

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Meetjain1**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
Closes #222 

## Description
[Please include a brief description of the changes or features added]

### Description:
This PR enhances the footer section of the website by adding the current copyright year, which is fetched dynamically. This ensures that the copyright year will always be up-to-date without requiring manual updates each year.

#### Changes:
1. **Footer HTML**: Updated the footer to include a placeholder for the copyright year.
2. **JavaScript**: Added a script to fetch the current year dynamically and insert it into the footer.
3. **CSS**: Ensured that the styling of the footer remains consistent with the new dynamic content.

#### Benefits:
- **Automation**: The copyright year updates automatically, reducing maintenance overhead.
- **Accuracy**: Ensures the displayed year is always current, improving the website's professionalism.

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Meetjain1** [comment]
@Sahil1786 please review this pr .

**Comment by Meetjain1** [comment]
@Sahil1786

**Comment by Meetjain1** [comment]
> Update Footer to Include Dynamic Copyright Year

Added copyright section

**Comment by Meetjain1** [comment]
> What have you fixed ?

@Sahil1786 fixed static copyright year bug , it will update automatically now that is it will auto fetch the current year 

petari

pet2

**Comment by Meetjain1** [comment]
before this pr 

pet4

**Comment by Meetjain1** [comment]
@Sahil1786 please review before gssoc ends . Thanks

**Comment by Meetjain1** [comment]
> @Sahil1786 please review before gssoc ends . Thanks

@Sahil1786 sir , please review this pr .

**Comment by Meetjain1** [comment]
Hello @Sahil1786

**Comment by Sahil1786** [comment]
Yes

**Pull request merged**
