### PR TITLE
Landing page with responsive added

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
Landing page with responsive added
issue #3 solved

https://github.com/Sahil1786/Petari/assets/125277258/9c729eac-e0b6-4a36-81be-4c38cb4172fa

### CODE REVIEW

**Comment by Sahil1786** [comment]
Need to fix the branch conflict error

**Comment by RamakrushnaBiswal** [comment]
@Sahil1786 how ? please tell me

**Comment by Sahil1786** [comment]
Need to fix the conflict

**Comment by RamakrushnaBiswal** [comment]
hi @Sahil1786  fixed the conflicts please check

**Comment by RamakrushnaBiswal** [comment]
hi @Sahil1786 add assigne and some lebels to it

**Pull request merged**
