### PR TITLE
converted ngo-dashboard internal css to external 

### PR DESCRIPTION
**Pull request by Pruthaa17**
#144

### CODE REVIEW

**Comment by Sahil1786** [comment]
provide some videos of your contrubution

**Comment by Pruthaa17** [comment]
Sure

**Comment by Pruthaa17** [comment]
NGO-Dashboard uses internal CSS

Screenshot (368)


NGO-Dashborad using external CSS

https://github.com/Sahil1786/Petari/assets/141839876/771a5c4f-3637-49c1-a7b2-de59992e0c6f

**Comment by Pruthaa17** [comment]
Windows screen recorder is not capturing chrome activities but after running the code no error is seen .

**Comment by Sahil1786** [comment]
logo is not showing after login the ngo

**Comment by Pruthaa17** [comment]
Screenshot (388)

**Pull request merged**
