### PR TITLE
Main

### PR DESCRIPTION
**Pull request by Tarunag03**
#issue 92 
added certification page perfectly working

### CODE REVIEW

**Comment by Sahil1786** [comment]
Need to fix the branch conflict error

**Comment by Sahil1786** [comment]
Need to fix the conflict

**Comment by Tarunag03** [comment]
> Need to fix the conflict

done

**Comment by sanjay-kv** [comment]
@Sahil1786 Most of your PR is labelled, + we have requested to add me into the repo so i can fix the labels.

**Pull request merged**
