### PR TITLE
Animations Added

### LINKED ISSUE #55: Adding Animation
**Is your feature request related to a problem? Please describe.**

Your landing page already looks fantastic, but incorporating animations could make it even more captivating. With my experience in this area, I'm eager to contribute to this enhancement.

**Describe the solution you'd like**

**Describe alternatives you've considered**

An animation on the image of your landing page which will keep on moving and will make you page look more Appealing

**Additional context**

Screenshot (116)
Screenshot (115)

What problem is this feature trying to solve?

How do we know when the feature is complete?

### PR DESCRIPTION
**Pull request by harshmishra19**
I have added the animation
This PR fixes #55

### CODE REVIEW

**Comment by Sahil1786** [comment]
Sow me the demo video of the animation that you added

**Comment by harshmishra19** [comment]
yes

**Comment by harshmishra19** [comment]
https://github.com/Sahil1786/Petari/assets/115486960/326c7e7f-0abc-4e65-919f-37fc4ef8576c

**Comment by Sahil1786** [comment]
you need to work on entire landing page

**Comment by harshmishra19** [comment]
Any specifications?

**Comment by Sahil1786** [comment]
What ever you want

**Pull request closed without merging**
