### PR TITLE
fixed query page CSS

### PR DESCRIPTION
**Pull request by dhairyagothi**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
#175 
## Description
fixed Query page CSS 
image

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@Sahil1786 please merge myPR

**Comment by dhairyagothi** [comment]
@Sahil1786 please merge PR

**Comment by dhairyagothi** [comment]
@Sahil1786 please merge this

**Comment by Sahil1786** [comment]
There are no changes

**Comment by dhairyagothi** [comment]
> There are no changes

Check contact form it is changed in mobile view 
Other things are same

**Comment by Sahil1786** [comment]
This branch has conflicts that must be resolved

**Pull request closed without merging**
