### PR TITLE
Documentation updated

### PR DESCRIPTION
**Pull request by pankaj-bind**
Issue Number #5 
Updated the document having everything regarding how to contribute to the project, code of conduct

### CODE REVIEW

**Comment by pankaj-bind** [comment]
some minor changes made

**Comment by Sahil1786** [comment]
You have to add project set up process

**Comment by pankaj-bind** [comment]
> You have to add project set up process

I did not understand. EJS and handlers are new for me will you tell me how you have setup this in your system, so that I can make changes

**Comment by Sahil1786** [comment]
How to setup the file .. like after downloading the project file .. install nmp i , Install Mongose ,  etc

**Comment by Sahil1786** [comment]
https://github.com/md-arin/Payment-App_MERN
 See this reference .. but this is a MERN stack based project

**Pull request merged**
