### PR TITLE
Navbar enhance

### PR DESCRIPTION
**Pull request by sanayamahajan-23**
## Related Issue
issue no 182

## Description
i add the floating action button navbar to enhance previous navbar

## Type of PR
- [x] Feature enhancemen

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by sanayamahajan-23** [comment]
i have fixed the navbar button now please review and merge the pr @Sahil1786

**Comment by sanayamahajan-23** [comment]
@Sahil1786 please look at the changes and merge the pr

**Comment by sanayamahajan-23** [comment]
please look at the pr @Sahil1786

**Comment by sanayamahajan-23** [comment]
only five days are left and our score is at risk please look at the pr @Sahil1786

**Comment by sanayamahajan-23** [comment]
@Sahil1786 please look at the pr sir my  score is at stake

**Comment by Sahil1786** [comment]
I will check by tonight

**Comment by Sahil1786** [comment]
still buttons are not working

**Comment by Sahil1786** [comment]
look into the navbar buttons

**Pull request closed without merging**
