### PR TITLE
Addition of Contributor's logo's and No of forks , pr's open closed s…

### PR DESCRIPTION
**Pull request by Anjaliavv51**
…tars contributor's to Readme.md file

issue #155

## Description
Addition of Contributor's logo's and No of forks , pr's open closed stars contributor's to Readme.md file

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

image

image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Sahil1786 please review the PR

**Comment by Anjaliavv51** [comment]
Please add level labels

**Comment by Anjaliavv51** [comment]
@Sahil1786

**Comment by Anjaliavv51** [comment]
Please add level labels and GSSOC
@Sahil1786

**Comment by Anjaliavv51** [comment]
@Sahil1786

**Comment by Anjaliavv51** [comment]
Please add level labels and GSSOC
@Sahil1786

**Comment by Anjaliavv51** [comment]
Please add level labels and GSSOC to the PR
@Sahil1786

**Comment by sailaja-adapa** [comment]
@Anjaliavv51 how did you installed the project in your laptop can u please explain when i am want to run the project i am getting issues

**Comment by Anjaliavv51** [comment]
@sailaja-adapa what is the issue u r facing exactly

**Comment by sailaja-adapa** [comment]
[nodemon] app crashed - waiting for file changes before starting... this was the issue i am facing

**Comment by Anjaliavv51** [comment]
@sailaja-adapa ur linkedin id please

**Comment by sailaja-adapa** [comment]
i think i am following you @Anjaliavv51

**Comment by sailaja-adapa** [comment]
https://www.linkedin.com/in/sailaja-adapa-770167291?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app

**Comment by Anjaliavv51** [comment]
@sailaja-adapa let me check

**Pull request merged**
