### PR TITLE
Added register-admin route, reading json data from body

### PR DESCRIPTION
**Pull request by dhananjaysingh10**
Issue #76 
solved the problem, admin data saving multiple time in DB
Added register-admin route
Saving password in encrypted form in DB
I have improved my code, please let me no if there are some error. I will try my best to fix them.

### CODE REVIEW

**Comment by dhananjaysingh10** [comment]
Sorry I closed the last PR by mistake, This PR has no merge conflict, also ADMIN Data is NOT Saved multiple times in DB.

**Comment by Sahil1786** [comment]
Show me some images

**Comment by dhananjaysingh10** [comment]
Pls check the attached images in sequence
1) Shown already registered user in MongoDB
Screenshot (59)

2) Tring to re register show error " Already registered, please login "
Screenshot (60)

3) Then i registered new user, 
Screenshot (61)

4) only one entry is created also you can not re register using that email
Screenshot (62)

5) response of /admin-login, showing successful login
Screenshot (63)

6) response of /admin-login when data is invalid or not found in DB
Screenshot (64)

**Comment by dhananjaysingh10** [comment]
Sir there is no username, in user schema, 
email
password
fullName
Mobile should we add it to schema, also register-admin route can be improved base on field required to register user and adding refresh token for validation , file upload like avatar for user.

All the schemas should be defined more precisely for ease of other developer so we do not need to revise the same portion of code again and again as our schema changes  
If you can provide the requirements i can design the schema on figma, after validation we can update the models code also.

**Comment by dhananjaysingh10** [comment]
Hello @Sahil1786 please let me know if there is any problem in the code

**Comment by Sahil1786** [comment]
branch has conflicts that must be resolved

**Comment by dhananjaysingh10** [comment]
@Sahil1786 please check it has no conflict right now

**Comment by dhananjaysingh10** [comment]
@Sahil1786 Please check my work and suggest changes if needed.
and I want to work on this part of the project suggested earlier in the comments
there is no username, in the user schema,
email
password
fullName
Mobile should we add it to the schema, also, the register-admin route can be improved based on the field required to register the user adding a refresh token for validation, and file upload like an avatar for the user and admin. 

All the schemas should be defined more precisely for the ease of other developers so we do not need to revise the same portion of code again and again as our schema changes
If you can provide the requirements I can design the schema, after validation we can update the MongoDB models also.

**Comment by dhananjaysingh10** [comment]
@Sahil1786 I did not get any points in GSSoC from my previous works, but I am still interested in working on this project. If you want us to contribute with the same enthusiasm, please tell us if there is any scope for improvement, as this wait has been quite unpleasant.

**Pull request merged**
